### ISSUE TITLE
remove donation links pointing  to UW

### ISSUE THREAD

**Issue by haraldschilly** [sagemath/website#168]

**Comment by kcrisman** [comment]
Is there no longer a "Sage Foundation" account there?  I've still gotten mail regarding that from UW in the recent past, but that could be incorrect.

**Comment by williamstein** [comment]
It ended when I resigned from UW.

**Comment by kcrisman** [comment]
> It ended when I resigned from UW.
>

Thanks for the update - hope they stop sending me mail now!

(OT to this thread is thus to restart threads on a proper Sage Foundation
via some other FLOSS foundation ...)

**Comment by williamstein** [comment]
On Tue, Jun 25, 2019, 7:49 AM kcrisman <notifications@github.com> wrote:

> > It ended when I resigned from UW.
> >
>
> Thanks for the update - hope they stop sending me mail now!
>

Sorry - this probably won't help.  They should (legally they must) have a
way to stop those emails.



> (OT to this thread is thus to restart threads on a proper Sage Foundation
> via some other FLOSS foundation ...)



+1

**Comment by haraldschilly** [comment]
+1 for coming up with our own foundation, or be part of another one.

>

**Comment by jhpalmieri** [comment]
I was just coming here to create this issue. Thanks for doing it already.

**Comment by haraldschilly** [comment]
links are removed, closing.

**Comment by jasongrout** [comment]
> +1 for coming up with our own foundation, or be part of another one.

NumFOCUS is a possibility.

**Comment by nthiery** [comment]
> NumFOCUS is a possibility.

+1.

From the contact I had, we presumably would be welcome there.

By the way: NumFOCUS Europe is in creation; the process is a bit slow
because NumFOCUS takes the occasion to cleanly lay out the legal
foundations for regional branches bound together by an international
entity. It would make sense to be part of it too, for donations from
Europe. Incidentally I probably will be part of the board.

Cheers,

		Nicolas
--
Nicolas M. Thiéry "Isil" <nthiery@users.sf.net>
http://Nicolas.Thiery.name/
