### ISSUE TITLE
Remove broken mirror ftp.kaist.ac.kr

### ISSUE THREAD

**Issue by mkoeppe** [sagemath/website#200]
It breaks our automated builds, please remove

https://trac.sagemath.org/ticket/30262#comment:3

**Comment by slel** [comment]
Fix at #201.

**Comment by slel** [comment]
The fix consists in marking the mirror as inactive for us.

I emailed the mirror maintainers (cc-ing Harald) to ask
an estimate for when the mirror might be back up.

If/when we hear it's back up we can mark it back as active.

**Comment by haraldschilly** [comment]
well, the scripts updating the mirrors wasn't running, that's why it was included erroneously

**Comment by slel** [comment]
Should we revert #201 then?

**Comment by haraldschilly** [comment]
well, it would be interesting to know if the problem was that this mirror was down or that random files were missing

**Comment by slel** [comment]
> well, it would be interesting to know if the problem was that this mirror was down or that random files were missing

By reverting #201 and seeing if it breaks automated builds again?

Sorry for not getting that, but can you clarify what you mean by
- the scripts updating the mirrors wasn't running, that's why it was included erroneously
- random files were missing

**Comment by haraldschilly** [comment]
> the scripts updating the mirrors wasn't running, that's why it was included erroneously

there is a period script being run, which indexes all known (and active) mirrors. it basically checks if they're up and the timestamp file is the expected one. this timestamp file also contains a hashsum for all contained files, so, it's more than just a timestamp. I'm not maintaining that timestamp file, though.

this script wasn't running in the past few days, but it should be up and running fine since yesterday.

> random files were missing

I don't know why this ticket here was made. what's the reason? can you define the problem, why this kaist mirror was reported to be removed? there must be a reason.

Once we know this reason, we can then investigate if the reported problem still exists or not.

If the problem no longer exists and there are no other indications that the mirror is a problem, I suggest to reinstate it as it was before. That's all.

**Comment by mkoeppe** [comment]
The problem is described in the ticket that I linked when I opened this issue.

**Comment by slel** [comment]
The KAIST server now correctly returns 404 for the e-antic tarball.
```
$ SAGE_SERVER=http://ftp.kaist.ac.kr/sage
$ wget $SAGE_SERVER/spkg/upstream/e_antic/e-antic-0.1.8.tar.gz
--2020-08-02 23:58:17--  http://ftp.kaist.ac.kr/sage/spkg/upstream/e_antic/e-antic-0.1.8.tar.gz
Resolving ftp.kaist.ac.kr (ftp.kaist.ac.kr)... 103.22.220.133
Connecting to ftp.kaist.ac.kr (ftp.kaist.ac.kr)|103.22.220.133|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-08-02 23:58:18 ERROR 404: Not Found.
```
Compare with the LIP6 server in Paris:
```
$ SAGE_SERVER=http://www-ftp.lip6.fr/pub/math/sagemath
$ wget $SAGE_SERVER/spkg/upstream/e_antic/e-antic-0.1.8.tar.gz
--2020-08-02 23:57:40--  http://www-ftp.lip6.fr/pub/math/sagemath/spkg/upstream/e_antic/e-antic-0.1.8.tar.gz
Resolving www-ftp.lip6.fr (www-ftp.lip6.fr)... 195.83.118.1
Connecting to www-ftp.lip6.fr (www-ftp.lip6.fr)|195.83.118.1|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-08-02 23:57:40 ERROR 404: Not Found.
```

So one would be tempted to go back to listing the mirror as active.

One objection to doing that, if I understand correctly, could be
that when that mirror is down, it sends the wrong HTTP status.

Should I try to clear that up with the mirror admins before setting
the KAIST mirror back to active in our list?
